default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 

development:
  <<: *default
  database: cipher_movies_development

test:
  <<: *default
  database: cipher_movies_test

production:
  <<: *default
